### ISSUE TITLE
No Sound ?

### ISSUE THREAD

**Issue by daslicht** [chrilith/RickJS#2]
Hi, 
is it normal that there is no sound ?

http://www.bigorno.net/xrick/xrickjs/

~ Marc

**Comment by chrilith** [comment]
Oh... should have sound as far as I remember :)
Well, will try to have a look at it. I'm impressed that it is still working since I changed some stuff in Gamalto.

Thank you for reporting this!

**Comment by daslicht** [comment]
I tried it yesterday locally , but it wasnt working. 
I cloned gamaldo but i get : 
```TypeError: undefined is not a constructor (evaluating 'new G.Vector()')```

**Comment by chrilith** [comment]
Well, well, well... right, I started a new version of Gamalto using ES6 but it is not complete and indeed I found some problems importing objects to this new project.

As for your error, it should be `G.Vector2()`, the `2` is missing.
Let me check.

**Comment by chrilith** [comment]
OK, did a quick dirty fix.
You must get the Gamalto source here: https://github.com/chrilith/Gamalto/releases/tag/RickJS-0.0.1.

This is a tag of an older version of Gamalto. Current code has changed a lot and is not compatible anymore with RickJS code.

Should work now with sound.

**Comment by daslicht** [comment]
awesome i try it !

**Comment by chrilith** [comment]
Hum, seems like a catching problem.
Or, did you also get the latest changes I made to RickJS?

I added a bad hack to make `G.Vector` work too at the start of `xrick.js file.

**Comment by daslicht** [comment]
got it now ! with sound . awesome !
Thank you

**Comment by chrilith** [comment]
Cool! 😎

**Comment by daslicht** [comment]
http://ansolas.de/exp/RickJS/play.html

**Comment by daslicht** [comment]
;)

**Comment by chrilith** [comment]
Okay :) I was wondering what you planed to do with it, now I know 👍

**Comment by daslicht** [comment]
Ha , I just wanted to try it , just for fun no plans at all :)
I played so many hours this games decides ago what a great game :)

And the second part is awesome as well :)
